version: '3.7'

services:
  frontend:
    container_name: frontend
    build: ./frontend
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    stdin_open: true
    command: npm start

  postgres:
    container_name: postgres
    restart: always
    image: postgres:latest
    volumes:
      - ./database:/var/lib/postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 'postgres'
